Algoritmo "EXC11L1"
//  Conhecido 3 números inteiros, apresente o resultado da
// multiplicação dos mesmos
Var
int_1, int_2, int_3, resultado: inteiro
Inicio
escreva("Insira o primeiro número inteiro: ")
leia(int_1)
escreva("Insira o segundo número inteiro: ")
leia(int_2)
escreva("Insira o terceiro número inteiro: ")
leia(int_3)
resultado <- int_1 * int_2 * int_3
escreva("O resultado da multiplicação é: ", resultado:4:2)
Fimalgoritmo