Algoritmo "EXC15L1"
// Sendo dado dois números pelo usuário, apresente a décima parte
// da subtração de um pelo outro, utilizando uma
// terceira variável.

// Baseado no exercício anterior, faça o mesmo processo
// sem fazer uso de uma terceira variável.
Var
primeiro, segundo: real
Inicio
escreva("Insira o primeiro número: ")
leia(primeiro)
escreva("Insira o segundo número: ")
leia(segundo)
escreva("O resultado é: ", (primeiro - segundo) / 10)
Fimalgoritmo