Algoritmo "EXC25L1"
// Construa um algoritmo que solicite três valores e apresente
// a soma de 46% do primeiro valor com com 31% do
// segundo valor com 14% do terceiro valor
Var
v1, v2, v3, soma: real
Inicio
escreva("Insira o primeiro valor ")
leia(v1)
escreva("Insira o segundo valor ")
leia(v2)
escreva("Insira o terceiro valor ")
leia(v3)
soma <- (v1 * 0.46) + (v2 * 0.31) + (v3 * 0.14)
escreva("O resultado é ", soma)
Fimalgoritmo