Algoritmo "EXC27L1"
// Construa um algoritmo que solicite o nome, a idade e o sexo
// (M, F, O) de uma pessoa e posteriormente apresente
// qual será o aumento (apenas o aumento) do salário com
// reajuste de 24,5%
Var
nome, sexo: caracter
idade: inteiro
salario: real
Inicio
escreva("Insira o nome ")
leia(nome)
escreva("Insira a idade ")
leia(idade)
escreva("Insira o sexo ")
leia(sexo)
escreva("Insira o salário ")
leia(salario)
escreva("O aumento será de ", salario * 0.245)
Fimalgoritmo